apiVersion: v1
kind: ConfigMap
metadata:
  name: pandemia-init-script
data:
  init-db.sh: |
    #!/bin/bash
    set -e

    mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
    CREATE DATABASE IF NOT EXISTS pandemia;
    CREATE USER IF NOT EXISTS 'pandemia'@'%' IDENTIFIED BY 'root';
    GRANT ALL PRIVILEGES ON pandemia.* TO 'pandemia'@'%';
    FLUSH PRIVILEGES;
    USE pandemia;

    CREATE TABLE IF NOT EXISTS continent (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(255) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS disease (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(255) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS country (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(255) NOT NULL,
        code3 VARCHAR(255),
        population BIGINT,
        continent_id INT,
        FOREIGN KEY (continent_id) REFERENCES continent(id)
    );

    CREATE TABLE IF NOT EXISTS region (
        id INT PRIMARY KEY AUTO_INCREMENT,
        country_id INT,
        name VARCHAR(255),
        FOREIGN KEY (country_id) REFERENCES country(id)
    );

    CREATE TABLE IF NOT EXISTS global_data (
        id INT PRIMARY KEY AUTO_INCREMENT,
        country_id INT,
        disease_id INT,
        date DATE,
        total_cases INT,
        new_cases INT,
        total_deaths INT,
        new_deaths INT,
        total_recovered INT,
        new_recovered INT,
        active_cases INT,
        serious_critical INT,
        total_tests BIGINT,
        tests_per_million INT,
        FOREIGN KEY (country_id) REFERENCES country(id),
        FOREIGN KEY (disease_id) REFERENCES disease(id)
    );
    EOF
