apiVersion: v1
kind: Secret
metadata:
  name: pandemia-elt-env
  namespace: pandemia-us
type: Opaque
stringData:
  DB_HOST: pandemia-bdd-service
  DB_USER: pandemia
  DB_PASSWORD: root
  DB_NAME: pandemia
  API_KEY: ihYY5!PWWK96JzUw@E^wBKAbMT49s*eX&Pnvq*5
  API_KEY_NAME: access_token
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: pandemia
  MYSQL_USER: pandemia
  MYSQL_PASSWORD: root
